name: CI check/test/build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare
        run: |
          npm install --legacy-peer-deps

      - name: Check
        run: |
          npm run lint
          npm run test

      - name: Build
        run: |
          npm run build
